### PR TITLE
Courtesy Charlie...

### PR DESCRIPTION
**Pull request by kapv89**

### CODE REVIEW

**Comment by rick** [comment]
Hey, Kapil -- good to hear from you!

For some reason I can't get the `ton.twitter.com/...` links to resolve.  Wondering if there's a way to just bring the images inline in the PR instead?

**Comment by kapv89** [comment]
Hey, Rick. Uploaded the images somewhere else.

**Comment by rick** [comment]
Not sure I understand the PR. Hope you're doing well. Cheers.

**Comment by kapv89** [comment]
Hey, I'm doing good. Failed to raise VC capital for a software I made. Living off the revenue. Have had a lot of free time on my hands past few months. Was being logically nostalgic the day I made this PR. :smiley_cat:

**Pull request closed without merging**
